### PR TITLE
Fix: Deploy a specific directory within repository 

### LINKED ISSUE #16: Deploy a specific directory within repository
**Describe your question**

Wondering if it is possible to make this action deploy from a specific directory which is being created by `npm` task. Say `build/plugin-slug`.

Based on [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun), if I changed the directory with `working-directory` keyword within workflow, would that work as expected?

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR supports deploying plugin files from a custom build directory by introducing a new flag `BUILD_DIR`:

- By default, `$BUILD_DIR` is set to `false`.
- If an absolute path was given, `$BUILD_DIR` will keep using that path.
- If a relative path was given, `$BUILD_DIR` will be concatenated with `$GITHUB_WORKSPACE`.

All files in the `BUILD_DIR` will be copied and deployed, and because those files are generated by a build command, there is no need to use `.disignore` or `.gitattribute` here.

Note: The asset files are still copied from the repository root directory.

Closes #16

### Alternate Designs
#30 #56

### Verification Process

This requires manual verification by deploying a real plugin using this branch.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Added - Custom build directory support.

### Credits

Props @dinhtungdu @mauryaratan

### CODE REVIEW

**Review by cadic — DISMISSED** [review]

File: deploy.sh [hunk 1]
```diff
@@ -38,6 +38,13 @@ if [[ -z "$ASSETS_DIR" ]]; then
 fi
 echo "ℹ︎ ASSETS_DIR is $ASSETS_DIR"
 
+if [[ -z "$BUILD_DIR" ]]; then
+	BUILD_DIR=false
+elif [[ $BUILD_DIR != /* ]]; then 
+	BUILD_DIR="${GITHUB_WORKSPACE%/}/${BUILD_DIR}"
+fi
+echo "ℹ︎ BUILD_DIR is $BUILD_DIR"
```
Comment (peterwilsoncc) [inline deploy.sh]:
```suggestion
if [[ -z "$BUILD_DIR" ]]; then
	BUILD_DIR=false
	echo "ℹ︎ Building from repository root directory"
elif [[ $BUILD_DIR != /* ]]; then 
	BUILD_DIR="${GITHUB_WORKSPACE%/}/${BUILD_DIR}"
	echo "ℹ︎ BUILD_DIR is $BUILD_DIR"
fi
```

Avoids `BUILD_DIR is false` message for something a little clearer

File: deploy.sh [hunk 2]
```diff
@@ -49,47 +56,53 @@ cd "$SVN_DIR"
...
+			/.gitattributes export-ignore
+			/.gitignore export-ignore
+			/.github export-ignore
+			EOL
+
+			# Ensure we are in the $GITHUB_WORKSPACE directory, just in case
+			# The .gitattributes file has to be committed to be used
+			# Just don't push it to the origin repo :)
+			git add .gitattributes && git commit -m "Add .gitattributes file"
+		fi
```
Comment (peterwilsoncc) [inline deploy.sh:98]: It might be worth ignoring `.gitignore` and `.gitattributes` in the build directory. They can be placed anywhere in a repo.

I am undecided, can you tell me why you decided not to do so?

File: deploy.sh [hunk 3]
```diff
@@ -49,47 +56,53 @@ cd "$SVN_DIR"
...
-
-	# This will exclude everything in the .gitattributes file with the export-ignore flag
-	git archive HEAD | tar x --directory="$TMP_DIR"
-
-	cd "$SVN_DIR"
 
-	# Copy from clean copy to /trunk, excluding dotorg assets
-	# The --delete flag will delete anything in destination that no longer exists in source
-	rsync -rc "$TMP_DIR/" trunk/ --delete --delete-excluded
+if [[ "$BUILD_DIR" = false ]]; then
```
Comment (peterwilsoncc) [inline deploy.sh:66]: What happens if BUILD_DIR = `` (empty string) or `./` (relative directory same as github repo's root directory?

What should happen?

**Review by peterwilsoncc — COMMENTED** [review]
One change suggestion to clarify messaging but otherwise I only have a couple of questions.

File: deploy.sh (hunk 2 above)
Comment (dinhtungdu) [reply deploy.sh:98]: @peterwilsoncc I decided not to use `.disignore` or `.gitattributes` because I assume that if plugin authors use `BUILD_DIR`, they are using a command/script to build the plugin, so anything inside `BUILD_DIR` is meant to be deployed. They have control over any files copied to that folder. Using `.disignore` or `.gitattributes` here can cause confusions IMO.

File: deploy.sh (hunk 3 above)
Comment (dinhtungdu) [reply deploy.sh:66]: In [43e313a](https://github.com/10up/action-wordpress-plugin-deploy/pull/83/commits/43e313a47ba97f1cce13f1bf7fa22c080f3c6812) I cover more possible value of `BUILD_DIR`:
- `./`
- `./some/directory`

The empty string case is handled already by `[[ -z "$BUILD_DIR" ]]` which returns `true` if `BUILD_DIR` is unset or set to the empty string.

IMO, `BUILD_DIR` is set by users so ultimately, it's users' responsibility to set the correct value for it. We already cover common use-cases in this PR.

File: deploy.sh (hunk 1 above)
Comment (dinhtungdu) [reply deploy.sh]: I addressed this in 43e313a, I decided to not echo anything if `BUILD_DIR` is `false` because it's the current behavior.

**Review by peterwilsoncc — APPROVED** [review]
Thanks Tung, this looks good to me.

I'm not sure how to test this so this is based on code review only, I haven't done any branch testing.
