### PR TITLE
fix shell glob in assets `svn propset` commands

### LINKED ISSUE #98: Assets svn propset commands fail
**Describe the bug**

The glob of `*.png`, `*.jpg`, `*.gif`, and `*.svg` in the `svn propset svn:mime-type` commands fail due to being quoted. SVN does not support expanding the globs itself, so we need to rely on the shell expanding them. Shell globs are only expanded when the `*` is unquoted, but currently the whole path including the glob is within quotes meaning that we're trying to pass the literal string `*.png` etc with the `*` unexpanded.

**Steps to Reproduce**

1. Ensure you have image assets in `.wordpress.org` directory in your plugin repo
2. Run the action
3. Check the logs
4. Scroll down to '➤ Copying tag...'
5. See error:

```plain
➤ Copying tag...
A         tags/4.3.0
'assets/*.png' is not under version control
svn: E155010: The node '/home/runner/svn-a-z-listing/assets/*.png' was not found.
'assets/*.jpg' is not under version control
svn: E155010: The node '/home/runner/svn-a-z-listing/assets/*.jpg' was not found.
'assets/*.svg' is not under version control
svn: E155010: The node '/home/runner/svn-a-z-listing/assets/*.svg' was not found.
```

**Expected behavior**

`svn propset` commands succeed

### PR DESCRIPTION
**Pull request by lucyllewy**
### Description of the Change

Unquote the globs in `svn propset svn:mime-type` commands to allow expansion by the shell

Closes #98

### Alternate Designs

None

### Possible Drawbacks

None

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/.github/blob/trunk/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

Fixed - failure to set assets mime-type with `svn propset`

### Credits

Props @diddledani

### CODE REVIEW

**Comment by jeffpaul** [comment]
@diddledani thanks for the issue and PR, we'll get this through review and get back to you with any questions or concerns!

File: deploy.sh [hunk 1]
```diff
@@ -135,16 +135,16 @@ svn cp "trunk" "tags/$VERSION"
 # Fix screenshots getting force downloaded when clicking them
 # https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/
 if test -d "$SVN_DIR/assets" && test -n "$(find "$SVN_DIR/assets" -maxdepth 1 -name "*.png" -print -quit)"; then
-    svn propset svn:mime-type "image/png" "$SVN_DIR/assets/*.png" || true
+    svn propset svn:mime-type "image/png" "$SVN_DIR/assets/"*.png || true
```
Comment (dinhtungdu) [inline deploy.sh:138]: I think we can remove the quote entirely instead of partial quoting the file path glob.
```suggestion
    svn propset svn:mime-type "image/png" $SVN_DIR/assets/*.png || true
```

Comment (dinhtungdu) [reply deploy.sh:138]: Same for other file types.

**Review by dinhtungdu — COMMENTED** [review]
Thanks so much, @diddledani, this is working as expected in my test. 🎉  I left a minor comment about the quote, can you please take a look?

File: deploy.sh (hunk 1 above)
Comment (lucyllewy) [reply deploy.sh:138]: I think it's best to leave it quoted as the variable `$SVN_DIR` is not guaranteed to never have spaces in its value. If GitHub change their setup, then the `$HOME` directory, which is used to generate the `$SVN_DIR` variable, might change to a location that includes a space. Therefore defensive programming suggests that we should retain the quotes to mitigate potential future breakage caused by platform changes.

Comment (dinhtungdu) [reply deploy.sh:138]: Make sense to me! Thanks so much for explanation!

**Review by dinhtungdu — APPROVED** [review]
